version: '3.9'

networks:
  keycloak:

volumes:
  keycloak-data:
  keycloak_logs:

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    restart: always
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
    command:
      - start-dev
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
      - keycloak_logs:/opt/jboss/keycloak/standalone/log

#  kafka:
#    container_name: kafka
#    image: bitnami/kafka:latest
#    restart: always
#    environment:
#      - KRAFT_CONTAINER_HOST_NAME=broker
#    ports:
#      - 9092:9092

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=provaAttus
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data